# Chapter 1
## Linear Algebra & Probability

In [2]:
import numpy as np # we need this to do linear algebra

# Matrices
Matrices are two-dimensional lists of numbers that contain rows and columns. Typically, rows in a matrix are denoted by i, while columns are denoted by j

In [6]:
matrix = np.array([[5, 6], [6, 9]])
print(matrix)

[[5 6]
 [6 9]]


# Tensors

While you may have heard of vectors and matrices before, the name tensor may be new. A tensor is a generalized matrix, and they have different sizes, or ranks, which measure their dimensions.

Tensors are three (or more)-dimensional lists; you can think of them as a sort of multi-dimensional object of numbers, such as a cube. Tensors have a unique transitive property and form; if a tensor transforms another entity, it too must transform. Any rank 2 tensor can be represented as a matrix, but not all matrices are automatically rank 2 tensors. A tensor must have this transitive property. As we'll see, this will come into play with neural networks in the next chapter. We can create tensors in Python such as the following: 

In [8]:
tensor = [[[1,2,3,4]],[[2,5,6,3]],[[7,6,3,4]]]
print(tensor)

[[[1, 2, 3, 4]], [[2, 5, 6, 3]], [[7, 6, 3, 4]]]


# Scalar Operations
Sclar operations involve a vector (or matrix) and a scalar.
To perform a scalar operation on a matrix, simply apply the scalar to every element of the matrix.

In [5]:
vector = np.array([[1, 2], [1, 2]])
for item in vector:
    print(item)

print('--------------------------------')

new_vector = vector + 2 # 2 is the scalar value
for item in new_vector:
    print(item)

[1 2]
[1 2]
--------------------------------
[3 4]
[3 4]


# Element-wise Operations

In element-wise operations, position matters. Values that correspond positionally are combined to create a new value.

In [10]:
vector_one = np.array([[1,2],[3,4]])
vector_two = np.array([[5,6],[7,8]])
print(vector_one + vector_two)
print('--------------------------------')
print(vector_one - vector_two)

[[ 6  8]
 [10 12]]
--------------------------------
[[-4 -4]
 [-4 -4]]


# Dot Product
The dot product is a special case of multiplication, and is rooted in larger theories of geometry that are used across the physical and computational sciences. It is a special case of a more general mathematical principle known as an inner product. When utilizing the dot product of two vectors, the output is a scalar.

In [12]:
vector_one = np.array([1,2,3])
vector_two = np.array([2,3,4])
print(np.dot(vector_one,vector_two)) # 20

20


# Hadamard Product
The Hadamard product, on the other hand, outputs a vector.


The Hadamard product is element-wise, meaning that the individual numbers in the new matrix are the scalar multiples of the numbers from the previous matrices. Looking back to Python, we can easily perform this operation in Python with a simple * operator

In [13]:
vector_one = np.array([1,2,3])
vector_two = np.array([2,3,4])
print(vector_one * vector_two) # [2, 6, 12]

[ 2  6 12]
